#!/bin/bash
export DSSSL=/usr/share/xml/docbook/stylesheet/nwalsh/xhtml/chunk.xsl

mkdir tmp
cd tmp
/usr/bin/xsltproc --stringparam html.stylesheet docbook.css ${DSSSL} ../book.xml
sed "s/{latest}/`date -u`/g" index.html >index.html.sed; mv index.html.sed index.html
mv *.html /home/neo/workspace/Development/public_html/book/developer/
cd ..
rm -rf tmp

